image: archlinux
tasks:
  - update-pacman: |
      sudo pacman -Sy
  - install-pkgs: |
      sudo pacman --noconfirm -S rust rust-analyzer pkg-config sqlite openssl gcc
  - build: |
      cd /home/build/grokloc-rust && cargo build --verbose
  - test: |
      cd /home/build/grokloc-rust && cargo test --verbose
  - clippy: |
      cd /home/build/grokloc-rust && cargo clippy --all-targets --all-features -- -D warnings
