image: "rust:latest"
test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
    - rustup component add clippy
    - cargo clippy --all-targets --all-features -- -D warnings
