//! env contains environment specific functions and symbols
use std::fmt;

#[allow(dead_code)]
pub const GROKLOC_ENV_KEY: &str = "GROKLOC_ENV";

/// Level describes the run level
#[derive(Debug, PartialEq)]
pub enum Level {
    Unit,
}

impl Default for Level {
    fn default() -> Self {
        Level::Unit
    }
}

impl fmt::Display for Level {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        // {:?} -> just use debug formatter generated by #[derive(Debug)]
        write!(f, "{:?}", self)
    }
}

/// Err covers level errors
#[derive(Debug, PartialEq)]
#[allow(dead_code)]
pub enum Err {
    UnknownLevel,
}

impl fmt::Display for Err {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "unknown level")
    }
}
